# Generated by Django 5.0 on 2024-02-09 22:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bills",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100)),
                ("amount", models.FloatField()),
                ("date", models.DateField(auto_now_add=True)),
                ("description", models.TextField()),
                ("dealer_name", models.CharField(blank=True, max_length=100)),
                ("dealer_phone", models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
