# Generated by Django 5.0 on 2024-02-09 23:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bills", "0002_bills_is_approved_bills_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="bills",
            name="category",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
