# Generated by Django 5.0 on 2024-02-10 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bills", "0003_bills_category"),
        (
            "projects",
            "0003_alter_project_client_city_alter_project_client_email_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="bills",
            name="projects",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="projects.project",
            ),
        ),
    ]
