# Generated by Django 5.0 on 2024-04-02 12:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasks",
            name="start_date",
            field=models.DateField(default=datetime.date(2024, 4, 2)),
        ),
    ]
