# Generated by Django 5.0 on 2024-02-10 01:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0002_alter_tasks_end_date_alter_tasks_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasks",
            name="category",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="end_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="start_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
