# Generated by Django 5.0 on 2024-02-02 16:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_project_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="client_city",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="client_email",
            field=models.EmailField(
                blank=True, default=None, max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="client_number",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
