# Generated by Django 5.0 on 2024-01-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_project_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="project",
            name="img_url",
            field=models.URLField(blank=True),
        ),
    ]
