# Generated by Django 5.0 on 2024-01-29 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0004_remove_project_img_url_project_img_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="img_data",
        ),
        migrations.AddField(
            model_name="project",
            name="img_url",
            field=models.URLField(blank=True),
        ),
    ]
