# Generated by Django 5.0 on 2024-01-29 17:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0005_remove_project_img_data_project_img_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="img_url",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
