# Generated by Django 5.0 on 2024-04-02 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contractor",
            name="img_url",
            field=models.TextField(blank=True),
        ),
    ]
