# Generated by Django 5.0 on 2024-02-02 16:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_contractor_name_alter_contractor_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractor",
            name="img_url",
            field=models.URLField(blank=True),
        ),
    ]
